DontBeLazy/DontBeLazy/Pages/Tasks/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DontBeLazy.Core;
using DontBeLazy.Data;

namespace DontBeLazy.Pages.Tasks
{
    public class DetailModel : PageModel
    {
        private readonly ITaskData taskData;

        [TempData]
        public string Message { get; set; }
        public MyTask MyTask { get; set; }

        public DetailModel(ITaskData taskData)
        {
            this.taskData = taskData;
        }

        public IActionResult OnGet(int taskId)
        {
            MyTask = taskData.GetById(taskId);
            if (MyTask == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();


        }
    }
}

DontBeLazy/DontBeLazy/Pages/Tasks/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DontBeLazy.Core;
using DontBeLazy.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DontBeLazy.Pages.Tasks
{
    public class EditModel : PageModel
    {
        private readonly ITaskData taskData;
        private readonly IHtmlHelper htmlHelper;

        [BindProperty]
        public MyTask MyTask { get; set; }

        public IEnumerable<SelectListItem> SelectType { get; set; }
        public EditModel(ITaskData taskData, IHtmlHelper htmlHelper)
        {
            this.taskData = taskData;
            this.htmlHelper = htmlHelper;
        }

        public IActionResult OnGet(int? taskId)
        {

            SelectType = htmlHelper.GetEnumSelectList<TaskType>();


            if (taskId.HasValue)
            {
                MyTask = taskData.GetById(taskId.Value);
            }

            else
            {
                MyTask = new MyTask();
            }

            if (MyTask == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        //OBRISI
        //On POst prima zadatak kojeg editiramo u POST FORMI, jer smo stavili da je MYTASK = BindProperty, tako da smo "uzeli" taj zadatak i dalje s njim
        // mozemo baratati u OnPost metodi, tako cu isto napraviti s "work" gumbom, koji ce mi biti on post :)
        public IActionResult OnPost()
        {
            SelectType = htmlHelper.GetEnumSelectList<TaskType>();

            if (ModelState.IsValid)
            {

                if (MyTask.Id > 0)
                {
                    MyTask = taskData.Update(MyTask);
                    TempData["Message"] = "Task updated!";


                }
                else
                {
                    MyTask = taskData.Add(MyTask);
                    TempData["Message"] = "Task saved!";

                }
                //taskData.Commit();
                return RedirectToPage("./Detail", new { taskId = MyTask.Id });
            }
            return Page();
        }
    }
}

DontBeLazy/DontBeLazy/Pages/Tasks/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DontBeLazy.Core;
using DontBeLazy.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace DontBeLazy.Pages.Tasks
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config; // config vjezba - OBRISATI
        private readonly ITaskData taskData;

        public string Message { get; set; } // config vjezba - OBRISATI
        public IEnumerable<MyTask> MyTask { get; set; }

        [BindProperty(SupportsGet =true)]
        public string SearchTerm { get; set; }


        public ListModel(IConfiguration config, ITaskData taskData)
        {
            this.config = config; // config vjezba - OBRISATI
            this.taskData = taskData;
        }
        public void OnGet()
        {
            //Message = config["Message"]; // config vjezba - OBRISATI
            MyTask = taskData.GetTasksByName(SearchTerm);
        }
      
    }
}

DontBeLazy/DontBeLazy/Pages/Tasks/Statistics.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DontBeLazy.Core;
using DontBeLazy.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DontBeLazy.Pages.Tasks
{
    public class StatisticsModel : PageModel
    {
        private readonly ITaskData taskData;
        

        public IEnumerable<TaskStatistics> TaskStat { get; set; }

        public StatisticsModel(ITaskData taskData)
        {
            this.taskData = taskData;
        }

        public void OnGet()
        {
            TaskStat = taskData.GetStatistics();
        }
    }
}

DontBeLazy/DontBeLazy/Pages/Tasks/WorkOnTask.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DontBeLazy.Core;
using DontBeLazy.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DontBeLazy.Pages.Tasks
{
    public class WorkOnTaskModel : PageModel
    {
        private readonly ITaskData taskData;

        [BindProperty(SupportsGet =true)]
        public MyTask MyTask { get; set; }

        [BindProperty(SupportsGet =true)]
        public TaskStatistics TaskStat { get; set; }




        public WorkOnTaskModel(ITaskData taskData)
        {
            this.taskData = taskData;
        }

        
        public IActionResult OnGet(int taskId)
        {

            MyTask = taskData.GetById(taskId);
            
            if (MyTask == null)
            {
                return RedirectToPage("./NotFound");   
            }

            TaskStat = taskData.AddNewLine(TaskStat, DateTime.Now.ToString(), DateTime.Now.ToString());

            //TaskStat.StartTime = DateTime.Now.ToString();

            return Page();
        }


        
        public IActionResult OnPost(int id)
        {
            TaskStat = taskData.GetStatByTaskId(id);
            TaskStat = taskData.UpdateWorkTime(TaskStat, DateTime.Now);

            return RedirectToPage("./Statistics");

        }


    }
}

DontBeLazy/DontBeLazy/ViewComponents/TasksSummaryViewComponent.cs
using DontBeLazy.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DontBeLazy.ViewComponents
{
    public class TasksSummaryViewComponent : ViewComponent
    {
        private readonly ITaskData taskData;

        public TasksSummaryViewComponent(ITaskData taskData)
        {
            this.taskData = taskData;
        }

        public IViewComponentResult Invoke()
        {
            var result = taskData.TasksSummary();
            return View(result);
        }
    }
}

DontBeLazy/DontBeLazy/Pages/Tasks/Detail.cshtml
@page "{taskId:int}"
@model DontBeLazy.Pages.Tasks.DetailModel
@{
    ViewData["Title"] = "Details";
}



@if (TempData["message"] != null)
{
    <div class="col-sm-8">
        <div class="alert alert-primary">
            @TempData["message"]
        </div>
    </div>
}



<h1>@Model.MyTask.Name</h1>

<div>
    Id: @Model.MyTask.Id
</div>
<div>
    Due At: @Model.MyTask.DueAt
</div>
<div>
    Task Type: @Model.MyTask.TaskType
</div>

<br />

<a asp-page="./List" class="btn btn-primary">Back to Tasks</a>

DontBeLazy/DontBeLazy/Pages/Tasks/Edit.cshtml
@page "{taskId:int?}"
@model DontBeLazy.Pages.Tasks.EditModel
@{
    ViewData["Title"] = "Edit";
    var header = Model.MyTask.Id > 0 ? "Edit" : "Create";
}

<h2>@header Task:</h2>


<form method="post">
    <input type="hidden" asp-for="MyTask.Id" />
    <div class="form-group">
        <label asp-for="MyTask.Name"></label>
        <input asp-for="MyTask.Name" class="form-control" />
        <span asp-validation-for="MyTask.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="MyTask.DueAt"></label>
        <input asp-for="MyTask.DueAt" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="MyTask.TaskType"></label>
        <select class="form-control" asp-for="MyTask.TaskType"asp-items="Model.SelectType">
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

DontBeLazy/DontBeLazy/Pages/Tasks/List.cshtml
@page 
@model DontBeLazy.Pages.Tasks.ListModel
@{
    ViewData["Title"] = "Tasks";
}

<br />
<div style="color:#808080" >
    <p>Ovdje je prikaz svih projekata na kojima korisnik radi. Kako bi se dodao novi projekt, odabere se "Add Task" iz izbornika i popune podaci o tom projektu.</p>
    <p>Nakon dodavanja novog projekta, klikom na "Details" mogu se pogledati njegovi detalji ili izmijeniti neki podaci klikom na "Edit".</p>
    <p>Cilj aplikacije je bilježiti vrijeme provedeno na svakom od projekata, kako bi na kraju imali statistiku koliko je vremena trebalo da se određeni zadatak završi.
        Kako bi se to postiglo, svaki put kad korisnik želi raditi na nekom projektu, klikne na gumb "Work On Task". To će zabilježiti početak rada.
        Ukoliko je korisnik gotov s radom na projektu, klikom na "Stop" bilježi se vrijeme završetka i računa ukupno vrijeme provedeno na tom projektu, te
        ga aplikacija odvede na "Statistics" karticu.
    </p>
</div>
<br />

<h1>List of Tasks</h1>

<br />

<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" asp-for="SearchTerm" />
            <span class="input-group-btn">
                <button class="btn btn-info">Search</button>
            </span>
        </div>
    </div>
</form>




<table class="table">
    <tr>
        <td>Task Name</td>
        <td>Due At</td>
        <td>Task Type</td>
        <td></td>
        <td></td>
        <td></td>
        @*koje vrhunske html vjestine... skuzi kako produziti onu crtu bez ovih td*@

    </tr>
    @foreach (var task in Model.MyTask)
    { 
    <tr>
        <td>@task.Name</td>
        <td>@task.DueAt</td>
        <td>@task.TaskType</td>
        <td>
            <a class="btn btn-primary" asp-page="./Detail" asp-route-taskId="@task.Id">Details</a>
        </td>
        <td>
            <a class="btn btn-primary" asp-page="./Edit" asp-route-taskId="@task.Id">Edit</a>
        </td>
        <td>
            <a class="btn btn-primary" asp-page="./WorkOnTask" asp-route-taskId="@task.Id">Work On Task</a>
        </td>

    </tr>
    }
</table>



<div>@Model.Message</div>

DontBeLazy/DontBeLazy/Pages/Tasks/NotFound.cshtml
@page

@{
    ViewData["Title"] = "Not Found";
}


<h2>This task is not found!</h2>

<a asp-page="./List" class="btn btn-primary">See All Tasks</a>

DontBeLazy/DontBeLazy/Pages/Tasks/Statistics.cshtml
@page
@model DontBeLazy.Pages.Tasks.StatisticsModel
@{
    ViewData["Title"] = "Task Statistics";
}


<br />
<div style="color:#808080">
    <p>Ovdje je prikazana statistika rada na pojedinom projektu. U donjoj tablici zabilježeni su početak, kraj rada te ukupno vrijeme provedeno na radu na projektu.
       TaskId je trenutno tu umjesto naziva zadatka (jedna od stvari koje ću prve ispraviti na ovoj aplikaciji). </p>
    <p>Gornja tablica računa koliko je ukupno vremena utrošeno na rad na pojedinom projektu. To je samo dio statistike koji će ova aplikacija prikazivati (još nešto na čemu radim).</p>
    
</div>
<br />


<div>
    @await Component.InvokeAsync("TasksSummary")
</div>
<br />

<h2>Task Statistics</h2>

<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <td>Id</td>
            <td>Started Working</td>
            <td>Ended Working</td>
            <td>Total Work Time</td>
            <td>Task Id</td>
        </tr>
    </thead>
    <tbody>

        @foreach (var stat in Model.TaskStat)
        {
            <tr>
                <td>@stat.Id</td>
                <td>@stat.StartTime</td>
                <td>@stat.EndTime</td>
                <td>@Math.Round(stat.WorkTime, 2)</td>
                <td>@stat.TaskId</td>
            </tr>

        }
    </tbody>
</table>

DontBeLazy/DontBeLazy/Pages/Tasks/WorkOnTask.cshtml
@page "{taskId:int}"
@model DontBeLazy.Pages.Tasks.WorkOnTaskModel
@{
    ViewData["Title"] = "Work On Task";
}

<h2>Working on task: @Model.MyTask.Name </h2>

<br />

<h6>When done, just click the "Stop" button to mark your time.</h6>

<br />

<form method="get">

    @*<input type="hidden" asp-for="TaskStat.Id" />*@
    <div class="form-group">
        <label asp-for="TaskStat.Id"></label>
        <input asp-for="TaskStat.Id" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="TaskStat.StartTime"></label>
        <input asp-for=@DateTime.Now class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="TaskStat.TaskId"></label>
        <input asp-for="TaskStat.TaskId" class="form-control" />
    </div>

</form>


<form method="post">
    <div class="form-group">
        <div class="input-group">
           @* <label asp-for="TaskStat.Id"></label>*@
            <input type="hidden" value="@Model.TaskStat.Id" name="id" />
            <button type="submit" class="btn btn-secondary">Stop</button>
        </div>
    </div>
</form>